# Generated by Django 5.1.6 on 2025-05-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='message',
        ),
    ]
