# Generated by Django 5.1.6 on 2025-08-29 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_alter_connection_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='blocked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='connection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocker', 'blocked_at'], name='connections_blocker_b42905_idx'),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocked', 'blocked_at'], name='connections_blocked_94022e_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['sender', 'status'], name='connections_sender__2b1807_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['receiver', 'status'], name='connections_receive_ae718e_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['sender', 'receiver', 'status'], name='connections_sender__79aad2_idx'),
        ),
    ]
