# Generated by Django 5.1.6 on 2025-04-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('community_invite', 'Community Invite'), ('community_request', 'Community Request'), ('community_update', 'Community Update'), ('message', 'Message'), ('alert', 'Alert'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
