# Generated by Django 5.1.6 on 2025-06-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('community_invite', 'Community Invite'), ('community_request', 'Community Request'), ('community_update', 'Community Update'), ('message', 'Message'), ('alert', 'Alert'), ('connection_accepted', 'Connection Accepted'), ('custom', 'Custom'), ('private_message', 'Private Message')], default='custom', max_length=20),
        ),
    ]
