# Generated by Django 5.1.6 on 2025-06-06 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_communitymessage_options_and_more'),
        ('notifications', '0007_alter_notification_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('community_invite', 'Community Invite'), ('community_request', 'Community Request'), ('community_update', 'Community Update'), ('message', 'Message'), ('alert', 'Alert'), ('connection_accepted', 'Connection Accepted'), ('custom', 'Custom'), ('private_message', 'Private Message'), ('community_message', 'Community Message')], default='custom', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('recipient', 'sender', 'community', 'notification_type')},
        ),
    ]
