# Generated by Django 5.1.6 on 2025-06-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_notification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('community_join_request_received', 'Community Join Request Received'), ('community_joined', 'Community Joined'), ('community_request_approved_by_admin', 'Community Request Approved By Admin'), ('community_invite', 'Community Invite'), ('community_update', 'Community Update'), ('message', 'Message'), ('alert', 'Alert'), ('connection_accepted', 'Connection Accepted'), ('connection_request', 'Connection Request'), ('custom', 'Custom'), ('private_message', 'Private Message'), ('community_message', 'Community Message'), ('product_message', 'Product Message'), ('event_start_notification', 'Event Start Notification')], default='custom', max_length=50),
        ),
    ]
