# Generated by Django 5.1.6 on 2025-07-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_notification_notification_type'),
        ('posts', '0004_post_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='posts.post'),
        ),
    ]
