# Generated by Django 5.1.6 on 2025-08-29 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_community_created_at_and_more'),
        ('notifications', '0021_alter_notification_notification_type'),
        ('posts', '0005_alter_comment_created_at_alter_like_created_at_and_more'),
        ('products', '0006_alter_product_closing_date_alter_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('community_join_request_received', 'Community Join Request Received'), ('community_joined', 'Community Joined'), ('community_request_approved_by_admin', 'Community Request Approved By Admin'), ('community_invite', 'Community Invite'), ('community_update', 'Community Update'), ('message', 'Message'), ('alert', 'Alert'), ('connection_accepted', 'Connection Accepted'), ('connection_request', 'Connection Request'), ('custom', 'Custom'), ('private_message', 'Private Message'), ('community_message', 'Community Message'), ('product_message', 'Product Message'), ('event_start_notification', 'Event Start Notification'), ('event_deleted', 'Event Deleted'), ('event_completed', 'Event Completed'), ('event_cancelled', 'Event Cancelled'), ('product_deleted', 'Product Deleted'), ('post_liked', 'Post Liked'), ('post_commented', 'Post Commented')], db_index=True, default='custom', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type', 'created_at'], name='notificatio_recipie_e8b7f3_idx'),
        ),
    ]
