# Generated by Django 5.1.6 on 2025-05-06 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('full_location', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='communityevent',
            name='location',
        ),
        migrations.AddField(
            model_name='communityevent',
            name='event_location',
            field=models.ForeignKey(blank=True, help_text='Only for offline events', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventlocation'),
        ),
    ]
