# Generated by Django 5.1.6 on 2025-05-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventlocation_remove_communityevent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='address',
            field=models.TextField(blank=True, help_text='Manually entered address by the user', null=True),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='banner',
            field=models.CharField(blank=True, help_text='Cloudinary public_id for the event banner (private image)', max_length=255, null=True),
        ),
    ]
