# Generated by Django 5.1.6 on 2025-05-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_communityevent_address_communityevent_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityevent',
            name='online_link',
        ),
    ]
