# Generated by Django 5.1.6 on 2025-05-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_communityevent_online_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
