# Generated by Django 5.1.6 on 2025-06-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_communityevent_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
