# Generated by Django 5.1.6 on 2025-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_communityevent_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityevent',
            name='notification_sent',
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
