# Generated by Django 5.1.6 on 2025-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_communityevent_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='event_status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Status of the event', max_length=10),
        ),
    ]
