# Generated by Django 5.1.6 on 2025-08-29 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_community_created_at_and_more'),
        ('events', '0008_communityevent_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='event_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='is_full',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='location_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='place_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='notification_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['community', 'start_datetime', 'event_status'], name='events_comm_communi_be5f58_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['created_by', 'start_datetime'], name='events_comm_created_7e3dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipation',
            index=models.Index(fields=['event', 'joined_at'], name='events_even_event_i_585e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipation',
            index=models.Index(fields=['user', 'joined_at'], name='events_even_user_id_ec15c6_idx'),
        ),
    ]
