# Generated by Django 5.1.6 on 2025-03-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number", max_length=15, null=True, unique=True),
        ),
    ]
