# Generated by Django 5.1.6 on 2025-03-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='farming_type',
            field=models.CharField(blank=True, help_text='Type of farming practiced', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='address',
            name='local_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='crops_grown',
        ),
        migrations.AddField(
            model_name='address',
            name='home_address',
            field=models.CharField(blank=True, help_text="User's general home address", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth", null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='location_address',
            field=models.CharField(blank=True, help_text="User's location address", max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='FarmingType',
        ),
    ]
