# Generated by Django 5.1.6 on 2025-03-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_farming_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='full_location',
            field=models.CharField(blank=True, help_text="Complete address details (e.g., '123 Main St, New York, USA')", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='location_name',
            field=models.CharField(blank=True, help_text="Short name of the location (e.g., 'New York')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(help_text='Country of the address', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude coordinate of the address', max_digits=9),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Longitude coordinate of the address', max_digits=9),
        ),
        migrations.AlterField(
            model_name='address',
            name='place_id',
            field=models.CharField(help_text='Unique ID from location API', max_length=50, unique=True),
        ),
    ]
