# Generated by Django 5.1.6 on 2025-03-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_country_alter_address_full_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
