# Generated by Django 5.1.6 on 2025-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(blank=True, help_text="Stores the secure Cloudinary URL for the user's profile picture.", max_length=255, null=True),
        ),
    ]
