# Generated by Django 5.1.6 on 2025-04-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_aadhar_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhar_resubmission_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
