# Generated by Django 5.1.6 on 2025-06-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banner_image',
            field=models.CharField(blank=True, help_text="Stores the secure Cloudinary URL for the user's banner image.", max_length=255, null=True),
        ),
    ]
