# Generated by Django 5.1.6 on 2025-07-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='home_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
