# Generated by Django 5.1.6 on 2026-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_address_country_alter_address_full_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='place_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
