# Generated by Django 5.1.6 on 2025-04-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembership',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('left', 'Left'), ('ignored', 'Ignored')], default='pending', max_length=10),
        ),
    ]
