# Generated by Django 5.1.6 on 2025-04-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communitymembership_joined_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymembership',
            old_name='join_message',
            new_name='message',
        ),
    ]
