# Generated by Django 5.1.6 on 2025-04-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_join_message_communitymembership_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('left', 'Left'), ('ignored', 'Ignored'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked')], default='pending', max_length=10),
        ),
    ]
