# Generated by Django 5.1.6 on 2025-04-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-created_at']},
        ),
    ]
