# Generated by Django 5.1.6 on 2025-04-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_community_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('left', 'Left'), ('ignored', 'Ignored'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('requested', 'Requested')], default='pending', max_length=10),
        ),
    ]
