# Generated by Django 5.1.6 on 2025-04-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_communitymembership_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitymembership',
            options={'ordering': ['-updated_at', '-joined_at']},
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('left', 'Left'), ('ignored', 'Ignored'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('requested', 'Requested'), ('leaved', 'Leaved')], default='pending', max_length=10),
        ),
    ]
