# Generated by Django 5.1.6 on 2025-07-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_communitymessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
