# Generated by Django 5.1.6 on 2025-08-29 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_community_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='joined_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('left', 'Left'), ('ignored', 'Ignored'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('requested', 'Requested'), ('leaved', 'Leaved')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['created_by', 'is_private', 'is_deleted'], name='community_c_created_4ded69_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'status'], name='community_c_communi_daa2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['user', 'status'], name='community_c_user_id_d2b2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymessage',
            index=models.Index(fields=['community', 'timestamp'], name='community_c_communi_e8e204_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymessage',
            index=models.Index(fields=['user', 'timestamp'], name='community_c_user_id_2db06a_idx'),
        ),
    ]
