name: AgrFlow Backend CI/CD Deploy

on:
  push:
    branches: [ production-branch ]  # run every time when push to this branch 

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.IMAGE_NAME }}:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.IMAGE_NAME }}:latest
          docker stop web || true && docker rm web || true
          docker run -d \
            --name web \
            -p 8000:8000 \
            --env-file /home/ubuntu/.env \
            ${{ secrets.IMAGE_NAME }}:latest
